---
version: '3.9'

services:
  jenkins:
    image: 'bdg/jenkins:latest'
    build:
      context: './jenkins/'
      args:
        #- 'AUTH0_SAML_METADATA_URL'
        #- 'AUTH0_SAML_LOGOUT_URL'
        - 'AUTH0_OIDC_BASE_URL'
        - 'DOCKER_GROUP_GID'
        - 'JENKINS_PUBLIC_URL'
      cache_from:
        - 'jenkins/jenkins:lts-slim'
        - 'base'
        - 'jenkins'
        - 'bdg/jenkins:latest'
    container_name: 'jenkins'
    environment:
      #- 'AUTH0_SAML_METADATA_URL'
      #- 'AUTH0_SAML_LOGOUT_URL'
      - 'AUTH0_OIDC_BASE_URL'
      - 'CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/'  # pragma: allowlist secret
      - 'DB_NAME=jenkins'
      - 'DB_HOSTNAME=db'
      - 'DB_USERNAME=jenkins'
      - 'JENKINS_PUBLIC_URL'
      - 'TRY_UPGRADE_IF_NO_MARKER=true'
    ports:
      - '8080:8080'
    secrets:
      - 'auth0_jenkins_client_id'
      - 'auth0_jenkins_client_secret'
      - 'bootstrap_ssh_deploy_key'
      - 'db_jenkins'
    volumes:
      - 'jenkins-data:/var/jenkins_home'
      - './jenkins/casc_configs:/var/jenkins_home/casc_configs:ro'
      - './jenkins/builds:/builds:rw'
      - './jenkins/workspaces:/workspaces:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    depends_on:
      - db

  db:
    image: 'postgres:14-alpine'
    container_name: 'postgres'
    shm_size: '256m'
    environment:
      POSTGRES_PASSWORD_FILE: '/run/secrets/db_admin'
      PGDATA: '/data'
    healthcheck:
      test: ["/bin/sh", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    expose:
      - '5432'
    secrets:
      - db_admin
      - db_grafanaro
      - db_jenkins
      - db_monitor
    volumes:
      - 'db-data:/data:rw'
      - './db/initdb.d:/docker-entrypoint-initdb.d:ro'

  #nexus:
  #    Fails to set the permissions of /nexus-data/etc/ to nexus:nexus
  #  image: 'sonatype/nexus3:3.45.1'
  #  container_name: 'nexus'
  #  user: 'nexus'
  #  configs:
  #    - source: nexus_config
  #      target: /nexus-data/etc/nexus.properties
  #      uid: '200'
  #      gid: '200'
  #      mode: 0640
  #  environment:
  #    NEXUS_SECURITY_RANDOMPASSWORD: 'false'  # pragma: allowlist secret
  #  ports:
  #    - '8081:8081'
  #    - '18090:18090'
  #    - '18091:18091'
  #  ulimits:
  #    nofile:
  #    soft: 65536
  #      hard: 65536
  #  healthcheck:
  #    test: 'curl -qsSf -m 10 http://127.0.0.1:8081/service/rest/v1/status'
  #    interval: 30s
  #    timeout: 10s
  #    retries: 3
  #    start_period: 30s
  #  volumes:
  #    - 'nexus-data:/nexus-data:rw'
  #    - './nexus/etc/nexus.properties:/nexus-data/etc/nexus.properties:rw'

configs:
  nexus_config:
    file: ./nexus/etc/nexus.properties

secrets:
  auth0_jenkins_client_id:
    file: './auth0/Jenkins-Local.id'
  auth0_jenkins_client_secret:
    file: './auth0/Jenkins-Local.secret'
  bootstrap_ssh_deploy_key:
    file: './secrets/jenkins-bootstrap-deploy.secret'
  db_admin:
    file: './db/admin.secret'
  db_grafanaro:
    file: './db/grafanaro.secret'
  db_jenkins:
    file: './db/jenkins.secret'
  db_monitor:
    file: './db/monitor.secret'
  nexus_admin:
    file: './nexus/admin.secret'

volumes:
  db-data:
  jenkins-data:
  nexus-data:
