---
version: '3.9'

services:
  alertmanager:
    image: 'quay.io/prometheus/alertmanager:v0.27.0'
    container_name: 'alertmanager'
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --storage.path=/alertmanager
      - --cluster.listen-address=
    volumes:
      - 'alertmanager-data:/alertmanager'
      - './alertmanager/:/etc/alertmanager/:ro'
    ports:
      - '${ALERTMANAGER_PORT}:9093'
    healthcheck:
      test: ["CMD-SHELL", 'wget -q --spider http://127.0.0.1:9093/-/ready || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  grafana:
    image: 'grafana/grafana-oss:10.2.2'
    container_name: 'grafana'
    secrets:
      - db_grafanaro
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - './grafana/provisioning:/etc/grafana/provisioning:ro'
    environment:
      GF_ALERTING_ENABLED: 'false'
      GF_ANALYTICS_CHECK_FOR_UPDATES: 'false'
      GF_ANALYTICS_REPORTING_ENABLED: 'false'
      GF_ANALYTICS_FEEDBACK_LINKS_ENABLED: 'false'
      #GF_INSTALL_PLUGINS: ''
      #GF_LOG_FILTERS: 'rendering:debug'
      GF_LOG_LEVEL: 'warn'
      GF_LOG_MODE: 'console'
      #GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: ''
      #GF_PLUGINS_ENABLE_ALPHA: ''
      #GF_RENDERING_CALLBACK_URL: 'http://grafana:${GRAFANA_PORT}/'
      #GF_RENDERING_SERVER_URL: 'http://renderer:8081/render'
      GF_SERVER_ENABLE_GZIP: 'true'
      GF_SNAPSHOTS_EXTERNAL_ENABLED: 'false'
      GF_UNIFIED_ALERTING_ENABLED: 'true'
      # Disable all login prompts and security features
      # !!! THIS IS ONLY SUITABLE FOR LOCAL TESTING !!!
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_AUTH_BASIC_ENABLED: 'true'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_DISABLE_SIGNOUT_MENU: 'true'
      GF_SECURITY_DISABLE_GRAVATAR: 'true'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    ports:
      - '${GRAFANA_PORT}:3000'
    healthcheck:
      test: ["CMD-SHELL", 'wget -q --spider http://127.0.0.1:3000/api/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  victoria-metrics:
    image: 'victoriametrics/victoria-metrics:stable'
    container_name: 'vmetrics'
    command:
      - '-promscrape.config=/etc/victoria-metrics/prometheus.yml'
      - '-graphiteListenAddr=:2003'
      - '-promscrape.config.strictParse=false'
    secrets:
      - db_monitor
      - nexus_admin
      - sonar_web_systempasscode
    volumes:
      - 'victoria-metrics-data:/victoria-metrics-data'
      - './victoria-metrics:/etc/victoria-metrics:ro'
    ports:
      - '${VICTORIA_METRICS_PORT}:8428'
      - '${VICTORIA_METRICS_STATSD_PORT}:2003'

  vmalert:
    image: 'victoriametrics/vmalert:stable'
    container_name: 'vmalert'
    command:
      - -datasource.url=http://victoriametrics:8428   # VM-single addr for executing rules expressions
      - -remoteWrite.url=http://victoriametrics:8428  # VM-single addr to persist alerts state and recording rules results
      - -remoteRead.url=http://victoriametrics:8428  # VM-single addr for restoring alerts state after restart
      - -notifier.url=http://alertmanager:9093  # AlertManager addr to send alerts when they trigger
    secrets:
      - db_monitor
      - nexus_admin
      - sonar_web_systempasscode

  postgres_exporter:
    image: 'quay.io/prometheuscommunity/postgres-exporter:v0.15.0'
    container_name: 'pg_exporter'
    command:
      - --auto-discover-databases
    environment:
      DATA_SOURCE_URI: "db/postgres?sslmode=disable"
      DATA_SOURCE_USER: 'monitor'
      DATA_SOURCE_PASS_FILE: '/run/secrets/db_monitor'
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: 'true'
    expose:
      - '9187/tcp'
    healthcheck:
      test: ["CMD-SHELL", 'wget -q --spider http://127.0.0.1:9187/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    secrets:
      - db_monitor

  blackbox_exporter:
    image: 'quay.io/prometheus/blackbox-exporter:v0.24.0'
    container_name: 'blackbox_exporter'
    entrypoint: '/etc/blackbox_exporter/entrypoint.sh'
    command:
      - --config.file=/tmp/config.yml
    expose:
      - '9115/tcp'
    healthcheck:
      test: ["CMD-SHELL", 'wget -q --spider http://127.0.0.1:9115/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    secrets:
      - sonar_web_systempasscode
    volumes:
      - './blackbox:/etc/blackbox_exporter:ro'

volumes:
  alertmanager-data:
  grafana-data:
  victoria-metrics-data:

secrets:
  db_monitor:
    file: './db/monitor.secret'
  db_grafanaro:
    file: './db/grafanaro.secret'
  nexus_admin:
    file: './nexus/admin.secret'
  sonar_web_systempasscode:
    file: './sonarqube/web_systempasscode.secret'
