---
version: '3.8'

services:
  jenkins:
    image: 'bdg/jenkins:latest'
    build:
      context: './jenkins/'
      args:
        #- 'AUTH0_SAML_METADATA_URL'
        #- 'AUTH0_SAML_LOGOUT_URL'
        - 'AUTH0_OIDC_BASE_URL'
        - 'DOCKER_GROUP_GID'
        - 'JENKINS_PUBLIC_URL'
      cache_from:
        - 'jenkins/jenkins:lts-slim'
        - 'base'
        - 'jenkins'
        - 'bdg/jenkins:latest'
    container_name: 'jenkins'
    environment:
      #- 'AUTH0_SAML_METADATA_URL'
      #- 'AUTH0_SAML_LOGOUT_URL'
      - 'AUTH0_OIDC_BASE_URL'
      - 'CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/'  # pragma: allowlist secret
      - 'JENKINS_PUBLIC_URL'
      - 'JAVA_OPTS'
      - 'JENKINS_OPTS'
      - 'JENKINS_SLAVE_AGENT_PORT'
      - 'TRY_UPGRADE_IF_NO_MARKER=true'
    ports:
      - '8080:8080'
    secrets:
      - 'auth0_jenkins_client_id'
      - 'auth0_jenkins_client_secret'
      - 'bootstrap_ssh_deploy_key'
    volumes:
      - 'jenkins-data:/var/jenkins_home'
      - './jenkins/casc_configs:/var/jenkins_home/casc_configs:ro'
      - './jenkins/build:/build:rw'
      - './jenkins/workspace:/workspace:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'

  nexus:
    image: 'sonatype/nexus3:3.29.2'
    container_name: 'nexus'
    user: 'nexus'
    environment:
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
    ports:
      - '8081:8081'
      - '18090:18090'
      - '18091:18091'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: 'curl -qsSf -m 10 http://127.0.0.1:8081/service/rest/v1/status'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - 'nexus-data:/nexus-data'
      - './nexus/etc/nexus.properties:/nexus-data/etc/nexus.properties:rw'

secrets:
  auth0_jenkins_client_id:
    file: './auth0/Jenkins-Local.id'
  auth0_jenkins_client_secret:
    file: './auth0/Jenkins-Local.secret'
  bootstrap_ssh_deploy_key:
    file: './secrets/jenkins-bootstrap-deploy.secret'
  nexus_admin:
    file: './nexus/admin.secret'

volumes:
  jenkins-data:
  nexus-data:
