---
# https://dependencytrack.org/docker-compose.yml
# Mildly modified
version: '3.9'

#####################################################
# This Docker Compose file contains two services
#    Dependency-Track API Server
#    Dependency-Track FrontEnd
#####################################################

volumes:
  dependency-track:

secrets:
  monitor:
    file: './db/monitor.secret'
  db_dtrack:
    file: './db/dtrack.secret'

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver
    container_name: dtrack-api
    depends_on:
      - db
    environment:
      # The Dependency-Track container can be configured using any of the
      # available configuration properties defined in:
      # https://docs.dependencytrack.org/getting-started/configuration/
      # All properties are upper case with periods replaced by underscores.
      - SYSTEM_REQUIREMENT_CHECK_ENABLED=false
      #
      # Database Properties
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://db:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME
      - ALPINE_DATABASE_PASSWORD
      - ALPINE_DATABASE_POOL_ENABLED=true
      - ALPINE_DATABASE_POOL_MAX_SIZE=5
      - ALPINE_DATABASE_POOL_MIN_IDLE=0
      - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
      - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
      #
      # Optional LDAP Properties
      # - ALPINE_LDAP_ENABLED=true
      # - ALPINE_LDAP_SERVER_URL=ldap://ldap.example.com:389
      # - ALPINE_LDAP_BASEDN=dc=example,dc=com
      # - ALPINE_LDAP_SECURITY_AUTH=simple
      # - ALPINE_LDAP_BIND_USERNAME=
      # - ALPINE_LDAP_BIND_PASSWORD=
      # - ALPINE_LDAP_AUTH_USERNAME_FORMAT=%s@example.com
      # - ALPINE_LDAP_ATTRIBUTE_NAME=userPrincipalName
      # - ALPINE_LDAP_ATTRIBUTE_MAIL=mail
      # - ALPINE_LDAP_GROUPS_FILTER=(&(objectClass=group)(objectCategory=Group))
      # - ALPINE_LDAP_USER_GROUPS_FILTER=(member:1.2.840.113556.1.4.1941:={USER_DN})
      # - ALPINE_LDAP_GROUPS_SEARCH_FILTER=(&(objectClass=group)(objectCategory=Group)(cn=*{SEARCH_TERM}*))
      # - ALPINE_LDAP_USERS_SEARCH_FILTER=(&(objectClass=user)(objectCategory=Person)(cn=*{SEARCH_TERM}*))
      # - ALPINE_LDAP_USER_PROVISIONING=false
      # - ALPINE_LDAP_TEAM_SYNCHRONIZATION=false
      #
      # Optional OpenID Connect (OIDC) Properties
      - ALPINE_OIDC_ENABLED=true
      - ALPINE_OIDC_ISSUER=${AUTH0_TENANT_BASE_URL}/
      - ALPINE_OIDC_CLIENT_ID=${AUTH0_DTRACK_CLIENT_ID}
      - ALPINE_OIDC_USERNAME_CLAIM=${AUTH0_DTRACK_USERNAME_CLAIM}
      - ALPINE_OIDC_TEAMS_CLAIM=${AUTH0_DTRACK_TEAMS_CLAIM}
      - ALPINE_OIDC_USER_PROVISIONING=true
      - ALPINE_OIDC_TEAM_SYNCHRONIZATION=true
      #
      # Optional HTTP Proxy Settings
      # - ALPINE_HTTP_PROXY_ADDRESS=proxy.example.com
      # - ALPINE_HTTP_PROXY_PORT=8888
      # - ALPINE_HTTP_PROXY_USERNAME=
      # - ALPINE_HTTP_PROXY_PASSWORD=
      # - ALPINE_NO_PROXY=
      #
      # Optional HTTP Outbound Connection Timeout Settings. All values are in seconds.
      # - ALPINE_HTTP_TIMEOUT_CONNECTION=30
      # - ALPINE_HTTP_TIMEOUT_SOCKET=30
      # - ALPINE_HTTP_TIMEOUT_POOL=60
      #
      # Optional Cross-Origin Resource Sharing (CORS) Headers
      # - ALPINE_CORS_ENABLED=true
      # - ALPINE_CORS_ALLOW_ORIGIN=*
      # - ALPINE_CORS_ALLOW_METHODS=GET, POST, PUT, DELETE, OPTIONS
      # - ALPINE_CORS_ALLOW_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
      # - ALPINE_CORS_EXPOSE_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
      # - ALPINE_CORS_ALLOW_CREDENTIALS=true
      # - ALPINE_CORS_MAX_AGE=3600
      #
      # Optional metrics properties
      - ALPINE_METRICS_ENABLED=true
      - ALPINE_METRICS_AUTH_USERNAME
      - ALPINE_METRICS_AUTH_PASSWORD
      #
      # Optional environmental variables to enable default notification publisher templates override and set the base directory to search for templates
      # - DEFAULT_TEMPLATES_OVERRIDE_ENABLED=false
      # - DEFAULT_TEMPLATES_OVERRIDE_BASE_DIRECTORY=/data
      #
      # Optional configuration for the Snyk analyzer
      # - SNYK_THREAD_BATCH_SIZE=10
      #
      # Optional environmental variables to provide more JVM arguments to the API Server JVM, i.e. "-XX:ActiveProcessorCount=8"
      # - EXTRA_JAVA_OPTIONS=
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '${DTRACK_API_PORT}:8080'
    volumes:
        # Optional volume mount to override default notification publisher templates
      #- "/host/path/to/template/base/dir:/data/templates"
      - 'dependency-track:/data'
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    container_name: dtrack-fe
    environment:
      # The base URL of the API server.
      # NOTE:
      #   * This URL must be reachable by the browsers of your users.
      #   * The frontend container itself does NOT communicate with the API server directly, it just serves static files.
      #   * When deploying to dedicated servers, please use the external IP or domain of the API server.
      - API_BASE_URL=${DTRACK_API_URL}
      - OIDC_ISSUER=${AUTH0_TENANT_BASE_URL}/
      - OIDC_CLIENT_ID=${AUTH0_DTRACK_CLIENT_ID}
      - "OIDC_SCOPE=openid profile email roles"
      #- "OIDC_FLOW="
      #- "OIDC_LOGIN_BUTTON_TEXT=SSO"
      # volumes:
      # - "/host/path/to/config.json:/app/static/config.json"
    ports:
      - "${DTRACK_UI_PORT}:8080"
    restart: unless-stopped
