# config file version
apiVersion: 1

# https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-notification-policies

resetPolicies:
  - 1

policies:
  - orgId: 1
    receiver: AlertManager
    group_by: ['...']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
