---
jobs:
  - script: >
      folder('Admin') {
        description('Folder containing configuration and seed jobs')
      }
  - file: "${CASC_JENKINS_CONFIG}/jobs/seed.groovy"
  - script: >
      queue('Admin/Seed')
