---
jobs:
  - script: >
      folder('Admin') {
        description('Folder containing configuration and seed jobs')
      }
  - script: >
      pipelineJob('Admin/Configure') {
        definition {
          parameters {
            gitParam('revision') {
              type('BRANCH_TAG')
              sortMode('ASCENDING_SMART')
              defaultValue('origin/master')
            }
          }

          logRotator {
            numToKeep(20)
          }

          cpsScm {
            scm {
              git {
                remote {
                  github('bdellegrazie/jenkins-bootstrap', 'ssh')
                  credentials('jenkins_bootstrap_deploy_key')
                }
              }
            }
            scriptPath('jobDSL/AdminConfigure.groovy')
          }
        }
      }
