{
 "title": "Nexus",
 "description": "Nexus Dashboard",
 "tags": [ "nexus" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_dispatches[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_thread_states_daemon_count", "legendFormat": "threads" }
   ]
  },
  {
   "title": "http responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_responses[5m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "http requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_requests[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "jvm memory heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_heap_max", "legendFormat": "max" },
    { "expr": "jvm_memory_heap_used", "legendFormat": "used" }
   ]
  },
  {
   "title": "jvm memory total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_total_max", "legendFormat": "max" },
    { "expr": "jvm_memory_total_used", "legendFormat": "used" }
   ]
  },
  {
   "title": "jvm memory metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Metaspace_used",
     "legendFormat": "used"
    },
    { "expr": "jvm_memory_pools_Metaspace_max", "legendFormat": "max" }
   ]
  }
 ]
}