---
apiVersion: 1

delete_notifiers:
  - name: AlertManager
    uid: alertmanager
    orgId: 1

notifiers:
  - name: AlertManager
    type: prometheus-alertmanager
    uid: alertmanager
    orgId: 1
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      url: http://alertmanager:9093/
