---
modules:
  sonar_health:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      headers:
        Host: sonarqube
        Accept-Language: en-US
        Origin: blackbox-exporter
        X-Sonar-Passcode: '@sonar_web_systempasscode@'
      follow_redirects: false
      fail_if_ssl: true
      fail_if_not_ssl: false
      fail_if_body_not_matches_regexp:
        - '^{"health":"GREEN"'
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
